### ISSUE TITLE
provide basic adapters

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/tagl#7]
* [x] react.js
* [x] mithril.js

Feel free to add your preferred lib here

**Comment by abulvenz** [comment]
Hi Stephan, 

I like tagl a lot when dealing with mithril. When I needed an #id I first added e.g. `svg.class1['#id'](...)` which looks a bit odd. Then I altered the example function to
`const tagl_hyperscript = tagl( (tagName, classes, ...args) => {`
`    return m([tagName, ...classes].join('.').replace('.$', '#'), ...args)`
`});` 
which really enhanced the readability by being able to write `svg.class1.$id`. Maybe you like this.
Since this "library" is so tiny and those two existing adapter functions are not that expensive, can you add them somehow, so that you don't need to get/copy them for each project?

Ciao
Andi

**Comment by abulvenz** [comment]
Thanks for your reply. I create this that copy shortly after my post. 
I can still use it without any alterations, thanks to mithril and tagl stableness. :)
https://github.com/abulvenz/tagl-mithril
